apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: todo_list-web:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: todo-app-config
        - secretRef:
            name: todo-app-secrets
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        hostPath:
          path: \c\Users\hila0\todo_list
